### ISSUE TITLE
[META] docs: Add ecs-logging-go-zerolog to the Elastic doc build

### ISSUE THREAD

**Issue by simitt** [elastic/ecs-logging-go-zerolog#2]
## To do

- [x] Create asciidoc docs
- [x] Open PR in `elastic/docs` to add to the build 
- [x] Open infra ticket to add the `elasticsearch/ci docs` check to this repo
- [x] Add the `elasticsearch/ci docs` webhook to the repo
- [x] Link to published docs from README

@bmorelli25 I copy&pasted this todo-list from https://github.com/elastic/ecs-logging-go-zap/issues/20. Would you be available to help with the docs again here? 
cc @michel-laterman

**Comment by michel-laterman** [comment]
@bmorelli25, I think we can get started on docs

**Comment by bmorelli25** [comment]
Sounds good! @simitt is this something that should be ready for 7.14?

**Comment by simitt** [comment]
It is not tied to the release, but since the functionality is public, it would be great to get a first set of docs within the next weeks.
